name: pose-est
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch
  - torchvision
  - pip
  - pip:
    - numpy
    - scipy
    - matplotlib
    - opencv-python
    - Pillow
    - tqdm
    - pyyaml
    - torchinfo
    - ultralytics
    - timm
    - segment-anything
    - albumentations
    - easydict
    - pandas
    - jupyterlab
    - ipykernel
